on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  runner:
    runs-on: ubuntu-latest
    name: CF Data
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: 'Run my scripts'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd scripts
          npm ci
          npm run dashboard
          npm run data
        env:
          EMAIL: ${{ secrets.CF_EMAIL }}
          API_KEY: ${{ secrets.CF_API_KEY }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
