on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  runner:
    runs-on: ubuntu-latest
    name: CF Data
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm install
      - run: npm start
        env:
          EMAIL: ${{ secrets.CF_EMAIL }}
          API_KEY: ${{ secrets.CF_API_KEY }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      - name: 'Commit changes'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add data/
          git commit -m 'Updated Flags'
          git push origin main