on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch: {}

jobs:
  runner:
    runs-on: ubuntu-latest
    name: CF Data
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: 'Run my scripts'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd scripts
          npm ci
          npm run dashboard
          npm run data
          npm run graphql
        env:
          EMAIL: ${{ secrets.CF_EMAIL }}
          EMAIL_2: ${{ secrets.CF_EMAIL_2 }}
          API_KEY: ${{ secrets.CF_API_KEY }}
          API_KEY_2: ${{ secrets.CF_API_KEY_2 }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
